baseURL = "http://example.com/"
languageCode = "en-us"
title = "Rhino project"
theme = "hugograyscale"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
[params]
    # Provide some metadata for search and indexing services
    description = "수소 충전소 입지선정 프로젝트"

[Author]
    name = "Rhinoteam"
    email = "https://github.com/statkwon/rhino"
